### PR TITLE
If i do a mistake once again im gonna jump

### PR DESCRIPTION
**Pull request by Pandacat-sudoer**

### CODE REVIEW

**Comment by Yonle** [comment]
You do not actually need to open two pull requests if you open one that wants to merge your `master` branch...

So simply... If you do mistake in a PR, just commit new change in your branch, then your PR will did it is job for you...

**Comment by Yonle** [comment]
Fix your commit message and squash the three commits into single commit

```
git rebase -i commitidbeforenewones
```

**Comment by Yonle** [comment]
Also, I am not a monster. So you do not need to jump.

**Comment by Yonle** [comment]
If possible:

- Explain your `plase just use single quote instead of double quote it fix some bugs in some machine like mine`.
- Explain the `add some security things in index.js`. For cookie, `verify_sess` is NOT sensitive. Once you verified, the key is obsolete. Same thing happens when you do not verify after a minute.

**Comment by Yonle** [comment]
Captcha & verify session cookie is mostly handled in `captcha.js`, not `index.js`

**Comment by Pandacat-sudoer** [comment]
> Captcha & verify session cookie is mostly handled in `captcha.js`, not `index.js`

also is it the commit where i put the express-rate-limit, xss modules, and the sanitize-html lib?

**Comment by Pandacat-sudoer** [comment]
anyways how can i delete my before comment (PR)?

**Comment by Yonle** [comment]
> > Captcha & verify session cookie is mostly handled in `captcha.js`, not `index.js`
> 
> also is it the commit where i put the express-rate-limit, xss modules, and the sanitize-html lib?

You, What

IMG_20230505_155125_552

**Comment by Yonle** [comment]
Closing as nothing seems really changed in the backend. Open new PR if you really have some changes.

To reach me, You could either go to [my imageboard](https://yonle.lecturify.net), or check my [social media](https://yonle.lecturify.net/#socialmedia) section.

**Comment by Yonle** [comment]
You do not need to jump.

**Pull request closed without merging**
